[2024-12-24T04:52:44.277+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-24T04:52:44.287+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: namu_crawling.initialize_if_needed scheduled__2024-12-23T00:00:00+00:00 [queued]>
[2024-12-24T04:52:44.291+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: namu_crawling.initialize_if_needed scheduled__2024-12-23T00:00:00+00:00 [queued]>
[2024-12-24T04:52:44.291+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-24T04:52:44.299+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): initialize_if_needed> on 2024-12-23 00:00:00+00:00
[2024-12-24T04:52:44.304+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=307) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-24T04:52:44.305+0000] {standard_task_runner.py:72} INFO - Started process 310 to run task
[2024-12-24T04:52:44.306+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'namu_crawling', 'initialize_if_needed', 'scheduled__2024-12-23T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/namu_crawling_dag.py', '--cfg-path', '/tmp/tmp81wcwnhq']
[2024-12-24T04:52:44.306+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask initialize_if_needed
[2024-12-24T04:52:44.335+0000] {task_command.py:467} INFO - Running <TaskInstance: namu_crawling.initialize_if_needed scheduled__2024-12-23T00:00:00+00:00 [running]> on host 33f70545a420
[2024-12-24T04:52:44.378+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='namu_crawling' AIRFLOW_CTX_TASK_ID='initialize_if_needed' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-23T00:00:00+00:00'
[2024-12-24T04:52:44.379+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-24T04:52:44.379+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-24T04:52:44.379+0000] {logging_mixin.py:190} INFO - Current task name:initialize_if_needed state:running start_date:2024-12-24 04:52:44.287599+00:00
[2024-12-24T04:52:44.380+0000] {logging_mixin.py:190} INFO - Dag name:namu_crawling and current dag run status:running
[2024-12-24T04:52:44.380+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-24T04:52:44.405+0000] {logging_mixin.py:190} INFO - Error during initialization: Message: Service /home/***/.cache/selenium/chromedriver/linux64/131.0.6778.204/chromedriver unexpectedly exited. Status code was: 127
[2024-12-24T04:52:44.405+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/namu_crawling_dag.py", line 33, in initialize_and_fetch_recent
    crawler = NamuCrawler()
              ^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawling/sel.py", line 118, in __init__
    self.driver = webdriver.Chrome(options=self.chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 108, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 121, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.cache/selenium/chromedriver/linux64/131.0.6778.204/chromedriver unexpectedly exited. Status code was: 127

[2024-12-24T04:52:44.415+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-24T04:52:44.416+0000] {logging_mixin.py:190} INFO - Task start:2024-12-24 04:52:44.287599+00:00 end:2024-12-24 04:52:44.415257+00:00 duration:0.127658
[2024-12-24T04:52:44.416+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): initialize_if_needed> dag:<DAG: namu_crawling> dagrun:<DagRun namu_crawling @ 2024-12-23 00:00:00+00:00: scheduled__2024-12-23T00:00:00+00:00, state:running, queued_at: 2024-12-24 04:47:36.500793+00:00. externally triggered: False>
[2024-12-24T04:52:44.416+0000] {logging_mixin.py:190} INFO - Failure caused by Message: Service /home/***/.cache/selenium/chromedriver/linux64/131.0.6778.204/chromedriver unexpectedly exited. Status code was: 127
[2024-12-24T04:52:44.416+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=namu_crawling, task_id=initialize_if_needed, run_id=scheduled__2024-12-23T00:00:00+00:00, execution_date=20241223T000000, start_date=20241224T045244, end_date=20241224T045244
[2024-12-24T04:52:44.423+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-24T04:52:44.424+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task initialize_if_needed (Message: Service /home/airflow/.cache/selenium/chromedriver/linux64/131.0.6778.204/chromedriver unexpectedly exited. Status code was: 127
; 310)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/namu_crawling_dag.py", line 33, in initialize_and_fetch_recent
    crawler = NamuCrawler()
              ^^^^^^^^^^^^^
  File "/opt/airflow/dags/crawling/sel.py", line 118, in __init__
    self.driver = webdriver.Chrome(options=self.chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 108, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 121, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.cache/selenium/chromedriver/linux64/131.0.6778.204/chromedriver unexpectedly exited. Status code was: 127

[2024-12-24T04:52:44.439+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-24T04:52:44.452+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-24T04:52:44.455+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
